//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MfWebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AkademisyenlerSet
    {
        public int AkademiNo { get; set; }
        public string AdSoyad { get; set; }
        public string Calısmalar { get; set; }
        public string Bolum { get; set; }
        public string Dal { get; set; }
    }
}
