//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MfWebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FakultelerSet
    {
        public int FakulteNo { get; set; }
        public string FakulteAd { get; set; }
        public string FakulteDurum { get; set; }
        public int AKTS { get; set; }
    }
}
